export const HORIZON_URL =
  process.env.REACT_APP_HORIZON_URL ?? 'https://horizon-testnet.stellar.org';
export const SOROBAN_RPC_URL =
  process.env.REACT_APP_SOROBAN_RPC_URL ?? 'https://soroban-testnet.stellar.org';

export const CONTRACT_ADDRESS =
  process.env.REACT_APP_CONTRACT_ADDRESS ??
  'CAQBOJ52ZNZAKGBS7P3RIIL7VUMYRG7NTTOTSYZHEUZEZIXMNNNDNZG4';
export const SHOP_ADDRESS =
  process.env.REACT_APP_SHOP_ADDRESS ?? 'GDGP2QEIYLKNVQO5LSU24Z7Q7GY2JXRG2X4T2KP36VHGAFZDWX3XXYA2';
export const NATIVE_TOKEN_ADDRESS =
  process.env.REACT_APP_NATIVE_TOKEN_ADDRESS ??
  'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC';
